import './article-prose.css';
import { enhanceArticleHtml } from '../../lib/content/enhance-html';

/**
 * Renders cleaned migrated HTML inside a typography-styled wrapper.
 * The body_html is trusted: it was generated by our extraction pipeline
 * (allow-listed tags, attribute-pruned, image src already pointing at our
 * Storage). We do not re-sanitize on read.
 *
 * `enhanceArticleHtml` is a presentation-only pass that upgrades "index / hub"
 * pages (long lists of links) into a tidy directory layout. It is a no-op on
 * regular articles.
 */
export function ArticleBody({
  html,
  variant = 'standard',
}: {
  html: string | null | undefined;
  variant?: 'standard' | 'feature';
}) {
  if (!html) return null;
  const isFeature = variant === 'feature';
  const enhanced = enhanceArticleHtml(html, { curateFeatureImages: isFeature });
  return (
    <div
      className={isFeature ? 'article-body article-body--feature' : undefined}
      style={{ background: isFeature ? '#f7f8fb' : '#fff', position: 'relative' }}
    >
      <div 
        style={{ 
          position: 'absolute', 
          top: 0, 
          left: 0, 
          right: 0, 
          height: '250px', 
          background: 'linear-gradient(180deg, rgba(248,250,255,1) 0%, rgba(255,255,255,0) 100%)',
          pointerEvents: 'none' 
        }} 
      />
      <article
        className={`article-prose${isFeature ? ' article-prose--feature' : ''}`}
        style={{ 
          maxWidth: isFeature ? 940 : 760,
          margin: '0 auto', 
          padding: isFeature ? 'clamp(2rem, 5vw, 4.5rem)' : 'clamp(3rem, 7vw, 5rem) 1.5rem 5rem',
          position: 'relative',
          zIndex: 1
        }}
        dangerouslySetInnerHTML={{ __html: enhanced }}
      />
    </div>
  );
}
