-- COALESCE is SQL syntax and cannot be schema-qualified. Correct the
-- production enqueue function generated by the automatic-mode migration
-- without duplicating its full body in a second migration.
do $$
declare
  v_definition text;
begin
  select pg_catalog.pg_get_functiondef(
    'factpt_private.enqueue_paid_payment()'::regprocedure
  )
  into v_definition;

  if v_definition is null then
    raise exception 'FACT.pt enqueue function not found';
  end if;

  v_definition := pg_catalog.replace(
    v_definition,
    'pg_catalog.coalesce(',
    'coalesce('
  );
  execute v_definition;

  if pg_catalog.strpos(
    pg_catalog.pg_get_functiondef(
      'factpt_private.enqueue_paid_payment()'::regprocedure
    ),
    'pg_catalog.coalesce('
  ) > 0 then
    raise exception 'FACT.pt enqueue function still contains invalid COALESCE calls';
  end if;
end
$$;

revoke all on function factpt_private.enqueue_paid_payment()
  from public, anon, authenticated;
